### ISSUE TITLE
creation of locales to help to translate

### ISSUE THREAD

**Issue by PhilLAL** [JohnMcLear/ep_user_font_size#3]
Hi,
I would like to help to translate this plugin.
Is it possible to add locale files to contribute?

For french, "User Font Size" would be translated into "Taille de police utilisateur".
Thank you.

**Comment by PhilLAL** [comment]
up in case this issue has been missed :)

**Comment by ldidry** [comment]
Fixed in #4 

@JohnMcLear Could you publish a new release of the plugin so we can update it on our etherpad instances, please?

**Comment by JohnMcLear** [comment]
@ldidry what's your npm username please?  I will make you owner of package.

**Comment by JohnMcLear** [comment]
Published as ep_user_fontsize_version_2,  I deprecated both old packages that were on the wrong npm user account -_-

**Comment by ldidry** [comment]
Thank you for publishing it :slightly_smiling_face: 

So… do you still need my npm username?

If you still want to transfer the ownership, you can transfer it to [`framasoft`](https://www.npmjs.com/~framasoft), the non-profit I work for (would be better than my own account).

**Comment by JohnMcLear** [comment]
@ldidry done, is there any other plugins you want to be able to publish?  If so, make a list and email me it or comment here and I will add ``framasoft``

**Comment by ldidry** [comment]
Thank you :slightly_smiling_face: 

I’ll make a list soon.

**Comment by JohnMcLear** [comment]
yw

**Comment by ldidry** [comment]
Hello @JohnMcLear,

Sorry for the delay. We would like to be able to publish new versions for the following packages:
- https://www.npmjs.com/package/ep_spellcheck
- https://www.npmjs.com/package/ep_font_color
- https://www.npmjs.com/package/ep_font_size
- https://www.npmjs.com/package/ep_author_hover
- https://www.npmjs.com/package/ep_table_of_contents
- https://www.npmjs.com/package/ep_font_family
- https://www.npmjs.com/package/ep_comments_page
- https://www.npmjs.com/package/ep_page_view
- https://www.npmjs.com/package/ep_markdown

Thank you :slightly_smiling_face:

**Comment by JohnMcLear** [comment]
All done :)

**Comment by ldidry** [comment]
Thank you very much :+1:

**Comment by JohnMcLear** [comment]
Your welcome, thanks for the help maintaining things :)
